### ISSUE TITLE
NCSA/UofI License Violation

### ISSUE THREAD

**Issue by klange** [ilyachur/Yatak#19]
Hello Ilya,

It appears that several of your source files are derived from [my project](https://github.com/klange/toaruos/), but you've neglected to follow the terms of the license. In particular, none of your source files carry any indication of the original copyright, which is in violation of the requirement that any derived source code or binaries you distribute must carry with them the [license text](https://github.com/klange/toaruos/blob/strawberry-dev/LICENSE.md). Being compliant with a BSD-style license such as this is very simple, and this should be easily rectified.

**Comment by ilyachur** [comment]
Hello Kevin,

I am so sorry, but when I forked your project (2 years ago) I could not find licenses.  I added LICENSE.md file (https://github.com/ilyachur/Yatak/blob/master/LICENSE.md) where I said that my project based on source code ToAruOS (https://github.com/klange/toaruos).

**Comment by klange** [comment]
Our source tree was definitely in a bit of disarray back in 2013, though I'm pretty sure the license was in the kernel main.c and the root of the repository at the time. What you have now should be compliant with the license, though I should note if you update anything with newer sources we assigned copyright to the authors of individual files some time last year so things may be a bit different.

Thanks!

**Comment by ilyachur** [comment]
Good. Excuse me for the inconvenience caused.
